name: Deploy IPFS Chaton

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: IPFS Pinata deploy GitHub action      
        uses: popovoleksandr/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: 'My cat site'
          path: './resources'
          pinata-api-key: 4467b5c8031e0ebee1f6
          pinata-secret-api-key: ce4adf952f0dcdb3bd15f337d95c13f05e8c2ebf186a86625d65f5c7821710e3
          verbose: true
          remove-old: false
