name: Deploy IPFS Chaton

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: IPFS Pinata deploy GitHub action      
        uses: popovoleksandr/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: 'My cat site'
          path: './resources'
          pinata-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJlYTAxYWM3YS00YzZhLTQ5YTUtYjhmNy0zMGIyYjNmYzcwZmUiLCJlbWFpbCI6ImFsZXhhbmRyZS5iZXJuYXJkQGVkdS5kZXZpbmNpLmZyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siaWQiOiJGUkExIiwiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjF9LHsiaWQiOiJOWUMxIiwiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjF9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6ImQyNjQyZTdjZWRkNzQ2Yjk1OTZiIiwic2NvcGVkS2V5U2VjcmV0IjoiYTg0MWM1YTU1OTFmZTJmODU0NjQ1NjI3ZTFjMTIwMzVhMGI4ZTMxMzgyNzQwM2NmNDAzNWI1MTMxMTZlNjdjMiIsImlhdCI6MTcwNzY2MDQzM30.xEXM2AXwnm9YOhZNwlidqyacJpBnHrCSvolCUpNHPpM
          pinata-secret-api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJlYTAxYWM3YS00YzZhLTQ5YTUtYjhmNy0zMGIyYjNmYzcwZmUiLCJlbWFpbCI6ImFsZXhhbmRyZS5iZXJuYXJkQGVkdS5kZXZpbmNpLmZyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siaWQiOiJGUkExIiwiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjF9LHsiaWQiOiJOWUMxIiwiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjF9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6ImQyNjQyZTdjZWRkNzQ2Yjk1OTZiIiwic2NvcGVkS2V5U2VjcmV0IjoiYTg0MWM1YTU1OTFmZTJmODU0NjQ1NjI3ZTFjMTIwMzVhMGI4ZTMxMzgyNzQwM2NmNDAzNWI1MTMxMTZlNjdjMiIsImlhdCI6MTcwNzY2MDQzM30.xEXM2AXwnm9YOhZNwlidqyacJpBnHrCSvolCUpNHPpM
          verbose: true
          remove-old: false
